MVC_Hunde/Controllers/ConsultaController.cs
using MVC_Hunde.ProxyConsulta;
using MVC_Hunde.ProxyTratamiento;
using MVC_Hunde.ProxyEstado;
using MVC_Hunde.ProxyMedicina;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Hunde.Controllers
{
    public class ConsultaController : Controller
    {
        ServicioConsultaClient servicioConsulta = new ServicioConsultaClient();
        ServicioTratamientoClient servicioTratamiento = new ServicioTratamientoClient();
        ServicioEstadoClient servicioEstado = new ServicioEstadoClient();
        ServicioMedicinaClient servicioMedicina = new ServicioMedicinaClient();
        List<SelectListItem> tratamientos;
        List<SelectListItem> estadosPac;
        List<SelectListItem> medicinas;

        public void armarListas()
        {
            tratamientos = servicioTratamiento.listarTratamientos().ToList().ConvertAll(t =>
            {
                return new SelectListItem()
                {
                    Value = t.cod_trat.ToString(),
                    Text = t.nom_trat,
                    Selected = false
                };
            });
            estadosPac = servicioEstado.ListarEstados().ToList().ConvertAll(e =>
            {
                return new SelectListItem()
                {
                    Value = e.cod_estado.ToString(),
                    Text = e.est_nut,
                    Selected = false
                };
            });
            medicinas = servicioMedicina.ListarMedicinas().ToList().ConvertAll(m =>
            {
                return new SelectListItem()
                {
                    Value = m.cod_med.ToString(),
                    Text = m.nombre_medicina,
                    Selected = false
                };
            });
        }

        // GET: Consulta
        public ActionResult Index()
        {

            List<Consulta> consultas = new List<Consulta>();
            consultas = servicioConsulta.ListarConsultas().ToList();

            ViewBag.listarConsultas = consultas;
            ViewBag.estados = obtenerEstados();
            return View();
        }

        public ActionResult Filtrar(FormCollection fc)
        {
            //se toman os valores de los controles
            String criterio = fc["criterio"];
            String criterioEstado = fc["cboEstado"]; //combo estado
            String condicion = fc["condicion"]; //radiobutton seleccionado

            switch (condicion)
            {
                case "PorMascota":
                    ViewBag.listarConsultas = servicioConsulta.ConsultasPorMascota(criterio);
                    break;
                case "PorFecha":
                    ViewBag.listarConsultas = servicioConsulta.ConsultasPorFecha(Convert.ToDateTime(criterio));
                    break;
                case "PorMedico":
                    ViewBag.listarConsultas = servicioConsulta.ConsultasPorMedico(criterio);
                    break;
                case "PorEstado":
                    ViewBag.listarConsultas = servicioConsulta.ConsultasPorEstado(Convert.ToInt16(criterioEstado));
                    break;
                default:
                    ViewBag.listarConsultas = servicioConsulta.ListarConsultas();
                    break;
            }
            ViewBag.estados = obtenerEstados();
            return View("Index");
        }

        private List<SelectListItem> obtenerEstados()
        {
            return new List<SelectListItem>()
            {
                new SelectListItem { Text = "Seleccione estado", Value = "0" },
                new SelectListItem { Text = "Realizadas", Value = "1" },
                new SelectListItem { Text = "Pendientes", Value = "2" },
                new SelectListItem { Text = "Cancelada", Value = "3" }
            };
        }

        // GET:
        // equivalente a actualizar
        // al abrir pagina
        public ActionResult DetallesDeConsulta(Int16 codigo)
        {
            armarListas();
            Consulta consulta = servicioConsulta.VerDetallesDeConsulta(codigo);

            //ViewBag.tratamientos = new SelectList(servicioTratamiento.listarTratamientos(), "cod_trat", "nom_trat", consulta.cod_tratamiento);
            //ViewBag.estadosPac = new SelectList(servicioEstado.ListarEstados(), "cod_estado", "est_nutricional", consulta.estado);
            //ViewBag.medicinas = new SelectList(servicioMedicina.ListarMedicinas(), "cod_med", "nombre_medicina", consulta.cod_medicina);
            ViewBag.tratamientos = tratamientos;
            ViewBag.estadosPac = estadosPac;
            ViewBag.medicinas = medicinas;

            return View(servicioConsulta.VerDetallesDeConsulta(codigo));
        }

        // POST: Biblioteca/Edit/5
        // boton para enviar datos
        [HttpPost]
        public ActionResult DetallesDeConsulta(FormCollection collection)
        {
            try
            {
                armarListas();
                // TODO: Add update logic here
                Consulta consulta = new Consulta();

                consulta.fec_consulta = collection["fec_consulta"].Substring(0, 10);
                consulta.hora_consulta = collection["hora_consulta"].Substring(0, 5);
                consulta.cod_emp = collection["cod_emp"];
                consulta.nom_emp = collection["nom_emp"];
                consulta.cod_pac = collection["cod_pac"];
                consulta.nom_pac = collection["nom_pac"];
                consulta.tipo_pac = collection["tipo_pac"];
                consulta.raza_pac = collection["raza_pac"];
                consulta.color_pac = collection["color_pac"];
                consulta.cod_cli = collection["cod_cli"];
                consulta.nom_cli = collection["nom_cli"];
                consulta.conduta = collection["conduta"];
                consulta.est_nutricional = collection["est_nutricional"];
                consulta.actividad = collection["actividad"];

                consulta.cod_consulta = Convert.ToInt16(collection["cod_consulta"]);
                consulta.cod_tratamiento = Convert.ToInt16(collection["cod_tratamiento"]);
                consulta.estado = Convert.ToInt16(collection["estado"]);
                consulta.cod_medicina = Convert.ToInt16(collection["cod_medicina"]);
                consulta.observaciones = collection["observaciones"];
                //(codigoConsulta, codigoTratamiento, codigoEstado, codigoMedicina, observaciones);

                //ViewBag.tratamientos = new SelectList(servicioTratamiento.listarTratamientos(), "cod_trat", "nom_trat", consulta.cod_tratamiento);
                //ViewBag.estadosPac = new SelectList(servicioEstado.ListarEstados(), "cod_estado", "est_nutricional", consulta.estado);
                //ViewBag.medicinas = new SelectList(servicioMedicina.ListarMedicinas(), "cod_med", "nombre_medicina", consulta.cod_medicina);
                ViewBag.tratamientos = tratamientos;
                ViewBag.estadosPac = estadosPac;
                ViewBag.medicinas = medicinas;

                servicioConsulta.AgregarDetallesDeConsulta(consulta.cod_consulta, consulta.cod_tratamiento,
                    consulta.estado, consulta.cod_medicina, consulta.observaciones);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


    }
}

MVC_Hunde/Views/Consulta/DetallesDeConsulta.cshtml
@model MVC_Hunde.ProxyConsulta.Consulta

@{
    ViewBag.Title = "DetallesDeConsulta";
}

<h2>Detalles De Consulta</h2>

@using (Html.BeginForm("DetallesDeConsulta", "Consulta"))
{
    <div class="form-horizontal">
        <h4>Consulta</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.cod_consulta, "Codigo de Consulta: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cod_consulta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cod_consulta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nom_pac, "Mascota: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_pac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_pac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tipo_pac, "Tipo: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tipo_pac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tipo_pac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.raza_pac, "Raza: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.raza_pac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.raza_pac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.color_pac, "Color: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.color_pac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.color_pac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nom_cli, "Lo trajo: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_cli, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_cli, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nom_emp, "Lo atendió: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_emp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_emp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fec_consulta, "Fecha: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fec_consulta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fec_consulta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hora_consulta, "Hora: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hora_consulta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hora_consulta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.actividad, "Actividad: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.actividad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.actividad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.conduta, "Conducta: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.conduta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.conduta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cod_tratamiento, "Tratamiento: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("cod_tratamiento", (List<SelectListItem>)ViewBag.tratamientos, null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.cod_tratamiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estado, "Estado de la mascota: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("estado", (List<SelectListItem>)ViewBag.estadosPac, null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cod_medicina, "Medicina: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("cod_medicina", (List<SelectListItem>)ViewBag.medicinas, null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.cod_medicina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.observaciones, "Observaciones: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.observaciones, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.observaciones, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" name="DetallesDeConsulta" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC_Hunde/Views/Consulta/Index.cshtml
<!DOCTYPE html>
<html>
<body>
    <h3>LISTADO DE CONSULTAS CON FILTRO - VETERINARIA HUNDE</h3>
    @using (Html.BeginForm("Filtrar", "Consulta"))
    {
        <table cellpading="2" cellspacing="2" border="1" width="1100">
            <tr>
                <th>Seleccione tipo de criterio</th>
            </tr>
            <tr>
                <td>
                    <input type="radio" name="condicion" value="Todas" checked="true" />
                    <span>Todas</span>
                </td>
                <td>
                    <input type="radio" name="condicion" value="PorMascota" />
                    <span>Por Mascota</span>
                </td>
                <td>
                    <input type="radio" name="condicion" value="PorFecha" />
                    <span>Por Fecha</span>
                </td>
                <td>
                    <input type="radio" name="condicion" value="PorMedico" />
                    <span>Por Medico</span>
                </td>
                <td>
                    <input type="radio" name="condicion" value="PorEstado" />
                    <span>Por Estado</span>
                </td>

            </tr>
            <tr>
                <td>
                    <input type="text" name="criterio" />
                </td>
                <td>
                    @Html.DropDownList("cboEstado", (IEnumerable<SelectListItem>)ViewBag.estados)
                </td>
                <td>
                    <input type="submit" name="Buscar" />
                </td>
                <td></td>
                <td></td>
            </tr>
        </table>
    }
    <br />
    <br />


    <table cellpading="2" cellspacing="2" border="1" width="1100">
        <tr>
            <th>Codigo</th>
            <th>Fecha</th>
            <th>Hora</th>
            <th>Mascota</th>
            <th>Medico</th>
            <th>Cliente</th>
            <th>Estado</th>
            @*<th>Detalles</th>*@

        </tr>

        @foreach (var cons in ViewBag.listarConsultas)
        {
            <tr>
                <th>@cons.cod_consulta</th>
                <th>@cons.fec_consulta</th>
                <th>@cons.hora_consulta</th>
                <th>@cons.nom_pac</th>
                <th>@cons.nom_emp</th>
                <th>@cons.nom_cli</th>
                <th>@cons.estado</th>
                @*<th>
                        @Html.ActionLink("Detalles", "DetallesDeConsulta", new { codigo = cons.cod_consulta })
                    </th>*@
            </tr>
        }
    </table>
</body>
</html>