MVC_Hunde/Controllers/ReservasController.cs
using MVC_Hunde.ProxyConsulta;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Hunde.Controllers
{
    public class ReservasController : Controller
    {
        ServicioConsultaClient servicioConsulta = new ServicioConsultaClient();
        // GET: Reservas
        public ActionResult Index()
        {
            ViewBag.listarCitas = servicioConsulta.ListarCitas().ToList();
            ViewBag.estados = obtenerEstados();
            return View();
        }

        private List<SelectListItem> obtenerEstados()
        {
            return new List<SelectListItem>()
            {
                new SelectListItem { Text = "Seleccione estado", Value = "0" },
                new SelectListItem { Text = "Aceptada", Value = "1" },
                new SelectListItem { Text = "Pendientes", Value = "2" },
                new SelectListItem { Text = "Cancelada", Value = "3" }
            };
        }

        public ActionResult Filtrar(FormCollection fc)
        {
            //se toman os valores de los controles
            String criterio = fc["criterio"];//texto input
            String criterioEstado = fc["cboEstado"]; //combo estado
            String condicion = fc["condicion"]; //radiobutton seleccionado

            switch (condicion)
            {
                //case "PorMascota":
                //    ViewBag.listarCitas = servicioConsulta.ConsultasPorMascota(criterio);
                //    break;
                //case "PorFecha":
                //    ViewBag.listarCitas = servicioConsulta.ConsultasPorFecha(Convert.ToDateTime(criterio));
                //    break;
                //case "PorMedico":
                //    ViewBag.listarCitas = servicioConsulta.ConsultasPorMedico(criterio);
                //    break;
                case "PorEstado":
                    ViewBag.listarCitas = servicioConsulta.CitasPorEstado(Convert.ToInt16(criterioEstado));
                    break;
                default:
                    ViewBag.listarCitas = servicioConsulta.ListarCitas();
                    break;
            }
            ViewBag.estados = obtenerEstados();
            return View("Index");
        }



    }
}

MVC_Hunde/Views/Reservas/Index.cshtml
<!DOCTYPE html>
<html>
<body>
    <h3>LISTADO DE CONSULTAS CON FILTRO - VETERINARIA HUNDE</h3>
    @using (Html.BeginForm("Filtrar", "Reservas"))
    {
        <table cellpading="2" cellspacing="2" border="1" width="1100">
            <tr>
                <th>Seleccione tipo de criterio</th>
            </tr>
            <tr>
                <td>
                    <input type="radio" name="condicion" value="Todas" checked="true" />
                    <span>Todas</span>
                </td>
                @*<td>
                        <input type="radio" name="condicion" value="PorMascota" />
                        <span>Por Mascota</span>
                    </td>
                    <td>
                        <input type="radio" name="condicion" value="PorFecha" />
                        <span>Por Fecha</span>
                    </td>*@
                <td>
                    <input type="radio" name="condicion" value="PorEstado" />
                    <span>Por Estado</span>
                </td>

            </tr>
            <tr>
                @*<td>
                        <input type="text" name="criterio" />
                    </td>*@
                <td>
                    @Html.DropDownList("cboEstado", (IEnumerable<SelectListItem>)ViewBag.estados)
                </td>
                <td>
                    <input type="submit" name="Buscar" />
                </td>
                @*<td></td>
                    <td></td>*@
            </tr>
        </table>
    }
    <br />
    <br />


    <table cellpading="2" cellspacing="2" border="1" width="1100">
        <tr>
            <th>Codigo</th>
            <th>Fecha Reserva</th>
            <th>Fecha Solicitada</th>
            <th>Hora Solicitada</th>
            <th>Estado</th>
            <th>Cod. Cliente</th>

        </tr>

        @foreach (var cons in ViewBag.listarCitas)
        {
            <tr>
                <th>@cons.cod_cita</th>
                <th>@cons.fec_reserva</th>
                <th>@cons.fec_cita</th>
                <th>@cons.hor_cita</th>
                <th>@cons.est_cita</th>
                <th>@cons.cod_cli</th>
            </tr>
        }
    </table>
</body>
</html>